import http from "http";
import express from "express";
import userRoutes from "./routes/user.routes.js";
import productRoutes from "./routes/produt.routes.js";
import categoryRoutes from "./routes/category.routes.js"
import { connectDatabase } from "./config/db.config.js"

const app = express();

//* creating http server
const server = http.createServer(app);

const middleware = (req, res, next) => {
  console.log("middleware 1");
  next();
}

// connect database
connectDatabase();

//! using middleware
app.use(middleware);

app.use((req,res,next)=>{
  console.log("middleware 2")
  req.user = {
    name : "john doe"
  }
  next()
})

app.use((req,res,next)=>{
  console.log("middleware 3")
  console.log(req.user);
  if(req.user){
    next();
  }
  else {res.status(401).json({
    message: "Unauthorized. Access denied"
  })
}
})

app.use(express.json());

// ip -> 198.168.1.1


//* home -> get, / => <h1>home page</h1>
// app.get(path, handler)
app.get("/", (req, res) => {
  // res.send("<h1>Home page</h1>");
  res.status(200).json({
    message: "server is running",
    success: true,
    data: null,
  });
});

//! using routes
app.use("/users", userRoutes);

app.use("/products", productRoutes);

app.use("/categories",categoryRoutes);

server.listen(8080, "localhost", () => {
  console.log(`server is running at http://localhost:8080`);
  console.log("press ctrl+c to close the server");
});

app.use((err, req, res, next)=>{
  console.log(err)
  res.status(err?.statuscode ?? 500).json({
    message: err?.message ?? "something went wrong",
    success : false,
    data : null
  })
})

//? expressJs /nestjs->
// get/ users -> handler
// post/ users -> handler

// http://localhost:8080/users?name=john&page=1&limit=10

// req.params -> {}
// req.query -> {name:"john",page:"1",limit:"10"}
// req.body

//! REST api
//? REST -> Represenational state transfer
//? api -> Application programming interface

//? constraints of REST api
//* client-server -> separation of concerns. The client and server are separate entities that communicate with each other over a network. The client is responsible for the user interface and user experience, while the server is responsible for processing requests and managing data. This separation allows for greater flexibility and scalability in the application architecture.

//* cacheable -> responses from the server can be cached by the client or intermediate servers to improve performance and reduce latency. Caching can be done at various levels, including the client, server, or proxy servers. The server can include caching directives in the response headers to indicate how long the response can be cached and under what conditions it can be reused.
// cache-control

//* stateless -> it does not store any state about the client on the server side. Each request from the client to the server must contain all the information needed to understand and process the request. The server does not retain any session information between requests. every request is independent and it is treated as a new request. This means that the server does not remember any previous interactions with the client. Each request is self-contained and must include all necessary information for the server to fulfill it.

// token is generated by the server and sent to the client. The client includes this token in subsequent requests to authenticate itself. The server verifies the token to ensure that the request is coming from an authenticated client. This allows the server to maintain a stateless architecture while still providing secure access to resources.

//* layered architecure -> The architecture of a RESTful API can be organized into layers, with each layer responsible for a specific set of tasks. The client interacts with the API through a series of layers, which can include caching, authentication, and load balancing. Each layer can be implemented independently, allowing for greater flexibility and scalability in the application architecture.
// client - cdn, proxy , load balancer .. - server

// uniform interface
// route naming
// use noun
// use meaningful http methods -> GET, POST, PUT, PATCH, DELETE
// use meaningful response status code
//? 100 - 199 -> informational
//? 200 - 299 -> success ,
//  200 -> ok ,
// 201 -> created
// 202 -> accepted

//? 300 - 399 -> redirection
//? 400 - 500 -> client side error eg 404
// 400 -> bad request
// 401 -> unauthorized
// 403 -> forbidden
// 404 -> not found

//? 500 - 599 -> server side error eg 500,502 bad gateway
// 500 -> internal server error
// 502 -> bad gateway
// 503 -> service unavailable

//! endpoints
//? users
// get /users -> get all users

//! resources
// /dashboard -> {}


//* middleware
//? middleware is a function execute between request and response cycle. 
//? 1. has access to request and response object and next function in the application request-response cycle.
//? 2. can execute own logic
//? 3. can modify request and response object
//? 4. can end the request-response cycle

//* types of middleware
//* custom middleware -> user defined middleware
//? 1. application level middleware ->
//  app.use() -> executes for every request that is in the application
//? 2. router level middleware ->
//  router.use() -> executes for every request to that router 
//? 3. error handling middleware : (err,req,res,next) => { }
//  executes when an error occurs in the application

// req -> mid1 -> mid2 -> mid3 -> midN -> controller

//* third party middleware -> express.json(), express.urlencoded(), cors(), helmet() etc

//* mongodb
// NoSql
// prisma orm, typeorm, sequelize orm
// sqlbolt

// sql
// database -> database
// table -> collections
// column -> field
// row -> document